name: 'Render and Commit Resume'
description: 'Render and Commit Resume'
inputs:
  access-token:  
    description: 'Github App access toke'
    required: true
runs:
  using: "composite"
  steps:
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: resume.tex
        working_directory: ./
    - name: Rename example
      shell: bash
      run: |
        mv resume.pdf redacted-resume.pdf
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ inputs.access-token }}
      with:
          # The branch to create
          branch: resume-update
    - name: Stage changes
      shell: bash
      run: |
        git add redacted-resume.pdf
    - name: Commit
      uses: dsanders11/github-app-commit-action@v1
      with:
        message: 'automated resume update'
        token: ${{ inputs.access-token }}
    - name: Create PR
      shell: bash
      run: |
        gh pr create -B main -H resume-update --title 'Auto resume update' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ inputs.access-token }}