name: Build LaTeX document
on: 
  push:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: dorny/paths-filter@v3
        id: resume_changed
        with:
         filters: |
            resume:
              - resume.tex
      - name: Use redacted PII
        run: mv redacted-pii.tex pii.tex
      - name: Compile LaTeX document
        if: steps.resume_changed.outputs.workflows == 'true'
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume.tex
          working_directory: ./
      - name: Stage changes
        if: steps.resume_changed.outputs.workflows == 'true'
        run: |
          git add resume.pdf
      - name: Commit
        if: steps.resume_changed.outputs.workflows == 'true'
        uses: dsanders11/github-app-commit-action@v1
        with:
          message: 'feat: my changes'
          token: ${{ steps.app-token.outputs.token }}