name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: dorny/paths-filter@v3
        id: resume_changed
        with:
         branch: ${{ github.head_ref || github.ref_name }}
         filters: |
            resume:
              - resume.tex
      - name: Render and Commit Resume
        if: steps.resume_changed.outputs.resume == 'true'
        uses: ./.github/actions/render_and_commit_resume
        with:
          access-token: ${{ steps.app-token.outputs.token }}
          branch: ${{ github.head_ref || github.ref_name }}
